name: test
on: [push, pull_request]
jobs:
  test-cljs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/storybook-cljs
    steps:
      - uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: 'latest'
      - run: lein fmt
      - run: lein kondo

  test-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/storybook-cli
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './modules/storybook-cli/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run formatter check
        run: npm run fmt:check
      - name: Run linter
        run: npm run lint